# Generated by Django 2.2.7 on 2019-11-24 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightStatus',
            fields=[
                ('fl_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fli_no', serialize=False, to='postlog.FlightNum')),
                ('catering', models.CharField(max_length=9)),
                ('fuel', models.IntegerField()),
                ('pas_cnt', models.IntegerField()),
                ('Cleaning', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('dep_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_time', to='postlog.DepartureTime')),
                ('dest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desti', to='postlog.Destination')),
                ('park_bay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parki_bay', to='postlog.Parking')),
            ],
            options={
                'verbose_name_plural': 'Flight Status',
            },
        ),
    ]
