# Generated by Django 2.2.7 on 2019-11-24 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FlightNum',
            fields=[
                ('fl_no', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_bay', models.CharField(max_length=3, unique=True)),
                ('fl_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fl2', to='postlog.FlightNum')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest', models.CharField(blank=True, max_length=15)),
                ('fl_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fl1', to='postlog.FlightNum')),
            ],
        ),
        migrations.CreateModel(
            name='DepartureTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_time', models.CharField(max_length=9)),
                ('fl_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fl3', to='postlog.FlightNum')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('fl_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fl4', serialize=False, to='postlog.FlightNum')),
                ('inbound', models.CharField(blank=True, max_length=15)),
                ('arr_time', models.TimeField(blank=True, null=True)),
                ('airline', models.ForeignKey(max_length=15, on_delete=django.db.models.deletion.CASCADE, to='postlog.Airline')),
                ('dep_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postlog.DepartureTime')),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postlog.Destination')),
                ('park_bay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postlog.Parking')),
            ],
        ),
    ]
