# Generated by Django 2.2.7 on 2019-11-24 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pnr',
            fields=[
                ('pnr', models.CharField(max_length=9, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='passenger',
            fields=[
                ('pnr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='p2', serialize=False, to='passenger.pnr')),
                ('name', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('passport_no', models.CharField(max_length=10, unique=True)),
                ('fl_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postlog.FlightNum')),
            ],
        ),
    ]
